// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Abonemen struct {
	UserID       string `json:"userID"`
	SubscriberID string `json:"subscriberID"`
}

type Comment struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	VideoID     string `json:"videoId"`
	Comment     string `json:"comment"`
	CommentDate string `json:"commentDate"`
	Like        int    `json:"like"`
	Dislike     int    `json:"dislike"`
}

type Kategori struct {
	ID           string `json:"id"`
	CategoryName string `json:"categoryName"`
}

type Membership struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

type MembershipDetail struct {
	MembershipID string `json:"membershipId"`
	UserID       string `json:"userId"`
	Date         string `json:"date"`
	Bill         int    `json:"bill"`
}

type Playlist struct {
	ID      string `json:"id"`
	OwnerID string `json:"ownerID"`
	Title   string `json:"title"`
	Privacy bool   `json:"privacy"`
}

type PlaylistDetail struct {
	PlaylistID string `json:"playlistId"`
	VideoID    string `json:"videoID"`
}

type PlaylistSub struct {
	PlaylistID string `json:"playlistID"`
	UserID     string `json:"userID"`
}

type Reply struct {
	ID        string `json:"id"`
	CommentID string `json:"commentId"`
	UserID    string `json:"userId"`
	Reply     string `json:"reply"`
	ReplyDate string `json:"replyDate"`
	Like      int    `json:"like"`
	Dislike   int    `json:"dislike"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Pass         string `json:"pass"`
	ProfilePic   string `json:"profilePic"`
	MembershipID string `json:"membershipId"`
}

type Video struct {
	ID          string `json:"id"`
	UserID      string `json:"userID"`
	Link        string `json:"link"`
	Title       string `json:"title"`
	View        int    `json:"view"`
	Like        int    `json:"like"`
	Dislike     int    `json:"dislike"`
	DateUpload  string `json:"dateUpload"`
	DatePublish string `json:"datePublish"`
	Description string `json:"description"`
	Thumbnail   string `json:"thumbnail"`
	Category    int    `json:"category"`
	Label       string `json:"label"`
	Privacy     bool   `json:"privacy"`
}

type NewCategory struct {
	CategoryName string `json:"categoryName"`
}

type NewComment struct {
	UserID  string `json:"userId"`
	VideoID string `json:"videoId"`
	Comment string `json:"comment"`
}

type NewMembership struct {
	Type string `json:"type"`
}

type NewMembershipDetail struct {
	MembershipID string `json:"membershipId"`
	UserID       string `json:"userId"`
	Bill         int    `json:"bill"`
}

type NewPlaylist struct {
	OwnerID string `json:"ownerID"`
	Title   string `json:"title"`
	Privacy bool   `json:"privacy"`
}

type NewPlaylistDetail struct {
	PlaylistID string `json:"playlistId"`
	VideoID    string `json:"videoID"`
}

type NewPlaylistSub struct {
	PlaylistID string `json:"playlistID"`
	UserID     string `json:"userID"`
}

type NewReply struct {
	CommentID string `json:"commentId"`
	UserID    string `json:"userId"`
	Reply     string `json:"reply"`
}

type NewSubscription struct {
	UserID       string `json:"userID"`
	SubscriberID string `json:"subscriberID"`
}

type NewUser struct {
	Username   string `json:"username"`
	Email      string `json:"email"`
	Pass       string `json:"pass"`
	ProfilePic string `json:"profilePic"`
}

type NewVideo struct {
	UserID      string `json:"userID"`
	Link        string `json:"link"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Thumbnail   string `json:"thumbnail"`
	Category    int    `json:"category"`
	Label       string `json:"label"`
	Privacy     bool   `json:"privacy"`
}
